### ISSUE TITLE
Expected output when extending a class that appears in more complex rules

### ISSUE THREAD

**Issue by adamwathan** [jonathantneal/postcss-extend-rule#5]
Hey Jonathan! I couldn't find this documented in the spec or the plugin but what is the expected behavior when you do something like this?

```css
.foo .bar {
  color: red;
}

.baz {
  @extends .bar;
}
```

Right now you get this output:

```css
.foo .bar {
  color: red;
}

.baz {
}
```

...where I was sort of expecting this:

```css
.foo .bar {
  color: red;
}

.foo .baz {
  color: red;
}
```

Is this by design?
